# hardware_params.yaml
# Hardware configurations for Earendil Bot (Encoder, IMU, Magnetometer, Motor)

# Magnetometer and Motor Configuration
hardware_bridge:
  ros__parameters:
    # Serial Port Settings
    port: "/dev/ttyUSBx"
    baudrate: 115200

    # Kinematics (For Odometry)
    wheel_radius: 0.15            # meters (URDF'ten alındı: wheel_link_radius = 0.15)
    wheel_separation: 0.7         # meters (URDF'ten alındı: body_link_y_dim (0.6) + wheel_link_length (0.1) = 0.7)
    ticks_per_rev: 341.2          # Encoder ticks per 1 full wheel revolution (Adjust for your specific motor gear ratio)
    
    # Magnetometer (Yaw Offset)
    heading_offset: 0.0           # degrees (Used to align magnetic north with robot's forward direction if needed)

    # Motor PWM Limits
    min_pwm: 60
    max_pwm: 90

# Infrared Sensor Configuration
ir_bridge:
  ros__parameters:
    port: "/dev/ttyUSBx"
    baud: 115200

# RTK GPS Node Configuration
rtk_node:
  ros__parameters:
    gps_port: "/dev/ttyUSBx"
    radio_port: "/dev/ttyUSBx"
    gps_baud: 460800
    radio_baud: 57600

# 2D Lidar Node Configuration
STL27L:
  ros__parameters:
    port_name: "/dev/ttyUSBx"
    port_baudrate: 921600