# hardware_params.yaml
# Hardware configurations for Earendil Bot

# Arduino Configuration
hardware_bridge:
  ros__parameters:
    # Serial Port Settings
    port: "/dev/ttyACM0"
    baudrate: 115200
    ir_height: 1.0                # meters (Height of the IR sensor from the ground)

    # Kinematics (For Odometry)
    wheel_radius: 0.15            # meters (Taken from URDF: wheel_link_radius = 0.15)
    wheel_separation: 0.7         # meters (Taken from URDF: body_link_y_dim (0.6) + wheel_link_length (0.1) = 0.7)
    ticks_per_rev: 341.2          # Encoder ticks per 1 full wheel revolution (Adjust for your specific motor gear ratio)
    
    # Magnetometer (Yaw Offset)
    heading_offset: 0.0           # degrees (Used to align magnetic north with robot's forward direction if needed)

    # Motor PWM Limits
    min_pwm: 60
    max_pwm: 90

# RTK GPS Node Configuration
rtk_node:
  ros__parameters:
    gps_port: "/dev/ttyUSBx"
    radio_port: "/dev/ttyUSBx"
    gps_baud: 460800
    radio_baud: 57600

# 2D Lidar Node Configuration
STL27L:
  ros__parameters:
    port_name: "/dev/ttyUSB0"
    port_baudrate: 921600