tunnel_navigator:
  ros__parameters:
    forward_speed_approach: 0.2
    forward_speed_tunnel: 0.3
    safety_speed: 0.1
    kp: 0.5
    kd: 1.0
    safety_threshold: 0.1
    tunnel_detection_threshold: 0.3
    sensor_height_from_ground: 1.0
    window_deg: 10.0
